### PR TITLE
[UPDATE] Added Rubycritic Gem

### LINKED ISSUE #15: Rubycritic gem installation to insurance the code quality
I verified that missing gems to insurance the code quality.

That's why I suggest that, please, install the [Rubycritic](https://github.com/whitesmith/rubycritic) gem in the project.

Observation: The configured minimum score must be the first score that the gem create.

Thanks. :smiley:

### PR DESCRIPTION
**Pull request by maniSHarma7575**
##### Explain the problem
---
Add RubyCritic to ensure the code quality is up to the threshold which means of good quality of course.
Observation: The configured minimum score must be the first score that the gem creates.

##### Explain the solution you implemented in detail
---
1. Added RubyCritic to ensure the code quality.
2. Added `.rubycritic.yml` config file to configured checks accordingly.
3.  Current minimum threshold score is set to  86.23 which is the initial score.

Running rubycritic with no arguments will analyse all the Ruby files in the entire directory:

```
$ rubycritic
```
#### Screenshots
---
1. Overview
15_rubycritic_overview
2. Code
15_rubycritic_code
3. Smells
15_rubycritic_smell
4. Console Output
15_rubycritic_console

Note: If you spot any issue around folder not being found, it will create a tmp folder inside the app. You might have to create a folder named compare and move the build_number.txt inside the folder(compare) and should be good.

##### Provide links to any relevant issue tickets, articles or other resources
---
https://github.com/whitesmith/rubycritic

This MR closes issue #15

### CODE REVIEW

**Comment by maniSHarma7575** [comment]
Closes #15

**Comment by maniSHarma7575** [comment]
@VictorSNA , @TecnoSigma Please review.

**Review by VictorSNA — APPROVED** [review]
Nice! Thanks for your contribution!

**Review by TecnoSigma — APPROVED** [review]

**Comment by TecnoSigma** [comment]
Tks @maniSHarma7575 ! :slightly_smiling_face:

**Pull request merged**
